# 0307

1. a(variable) = 1(content)

2. variable만 적었을 때 마지막 것만 나옴.
    1) 한 줄에 다 적고 싶을 때는 print(a)
    
3. run인 경우 --> 초록색 / shut down --> 회색 --> run 중지
    1) 이 경우 print(a) --> error 
    2) 다시 a,b 값 run --> error (x)
    
4. all output --> clear --> output 모두 없어짐.

## variable type

In [17]:
a = 1; print(type(a))

<class 'int'>


* int = 정수

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


* float = 소수점

In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


--> 미리 정하지 않고 어떤 것을 넣느냐에 따라 변화

--> 중간에 type만을 바꾸려면 int(a) / float(a) 이런 식으로.

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


* a = '123' or "123" -->  type = str(string)

* 0번째를 str의 첫 번째로 본다. ex) a[0] = 1 / a=[1] = 2

* [0]은 처음, -1은 가장 끝 (-2는? 끝에서 두번 째)

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


* a = [1,2,3] --> type = list

* 반드시 대괄호, 구분은 콤마로.

* b = [1,2,'a']도 list. --> 즉 list 안에는 모든 것이 들어갈 수 있다.

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


* type은 list

* a[0]은 첫 번째 = 1

* a[1]은 두 번째 = 2

* a[2]는 세 번째 =[3,'4']

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


* a = (1,2,3) --> type = tuple

* 나머지 tuple내 순서는 list와 동일

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


* type = dic(사전)

* print(a["a"]) = "a" 해당 단어 apple

In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

* list안 tuple 들어 있음


In [28]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


* array는 matrix와 비슷한 것.

* import는 package를 불러오는 것이므로 시간이 소요됨.

* out[27]과는 다르게 2x3 행렬처럼 결과가 바뀐다. 

* numpy는 행렬을 처리하는 단위.

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


* 만약 행렬이라면 2x3끼리 곱하기 불가하지만, In[29] 경우 곱하기가 가능하다.

* 따라서 array는 행렬과 비슷한 것이지 행렬과 동일한 것은 아님을 알 수 있다.

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


* c를 matrix로 변경함.

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

* matrix 변경 후에 곱하기를 하면 에러가 난다.

* 같은 배열을 가진 행렬을 곱할 수 없기 때문.

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

* T는 c를 뒤집어주는 역할.

* 즉 2x3에서 3x2로 변경함.